version: "3.8"

services:
  fastapi-app:
    build: ./backend/fastapi
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/fastapi:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - backend

  fastapi-app2:
    build: ./backend/fastapi2
    container_name: fastapi-app2
    ports:
      - "8001:8001"
    volumes:
      - ./backend/fastapi2:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - backend

  nodejs-app:
    build: ./backend/nodejs
    container_name: nodejs-app
    ports:
      - "3000:3000"
    volumes:
      - ./backend/nodejs:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://FYPUSERS:k1iTgwyFFzGlAkeN@fyptestdb.d7zdlnq.mongodb.net/TestAniket
    depends_on:
      - fastapi-app
      - fastapi-app2
    networks:
      - backend

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-app
      - fastapi-app2
      - nodejs-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
